lr: 0.001
num_hiddens: 128
batch_size: 64
num_heads: 4
num_layers: 2
ffn_num_hiddens: 128
dropout: 0.1
optimizer: adam
num_epoch: 8
log_freq: 1
data_path: "data/fra-eng"
num_steps: 10
num_train: 10000
num_val: 1000
device: "cuda"